# syntax=docker/dockerfile:1
FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -o /app/baxi-worker ./cmd/baxi-worker

# Final stage
FROM alpine:latest

RUN adduser -D -s /bin/sh appuser
RUN apk --no-cache add ca-certificates tzdata
ENV TZ=UTC

COPY --from=builder /app/baxi-worker /app/baxi-worker

USER appuser
CMD ["/app/baxi-worker"]
