package adapter

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"strings"
	"time"

	"baxi/internal/action"
)

const defaultGitHubBaseURL = "https://api.github.com"

// GitHubIssue represents the payload for creating or updating a GitHub issue.
type GitHubIssue struct {
	Title  string   `json:"title"`
	Body   string   `json:"body"`
	Labels []string `json:"labels,omitempty"`
}

// GitHubComment represents a comment to be added to a GitHub issue.
type GitHubComment struct {
	Body string `json:"body"`
}

// GitHubAdapter dispatches action proposals to GitHub (via API).
type GitHubAdapter struct {
	config     GitHubConfig
	httpClient *http.Client
	token      string
	baseURL    string
}

// NewGitHubAdapter creates a new GitHubAdapter with the given config.
func NewGitHubAdapter(config GitHubConfig) *GitHubAdapter {
	return &GitHubAdapter{
		config:     config,
		httpClient: &http.Client{Timeout: 30 * time.Second},
		token:      config.Token,
		baseURL:    defaultGitHubBaseURL,
	}
}

// BuildLabels extracts label names from the proposal payload.
// It returns ["alert", severity, owner] matching the Python adapter.
func (a *GitHubAdapter) BuildLabels(payload map[string]interface{}) []string {
	severity := getString(payload, "severity", "medium")
	owner := getString(payload, "owner_role", "unassigned")

	labels := []string{"alert", severity, owner}

	// Deduplicate and filter empty strings
	seen := make(map[string]bool)
	result := make([]string, 0, len(labels))
	for _, label := range labels {
		label = strings.TrimSpace(label)
		if label != "" && !seen[label] {
			seen[label] = true
			result = append(result, label)
		}
	}
	return result
}

// BuildIssue formats an ActionProposal into a GitHubIssue payload.
// It mirrors the Python GitHubIssueAdapter.dry_run() behaviour.
func (a *GitHubAdapter) BuildIssue(proposal action.ActionProposal) GitHubIssue {
	payload := proposal.Payload

	ruleID := getString(payload, "rule_id", "unknown")
	metric := getString(payload, "metric_name", "metric")
	current := getString(payload, "current_value", "N/A")
	baseline := getString(payload, "baseline_value", "N/A")
	change := getFloat(payload, "change_rate", 0)
	severity := getString(payload, "severity", "medium")
	owner := getString(payload, "owner_role", "unassigned")

	title := fmt.Sprintf("[Alert] %s: %s anomaly detected", ruleID, metric)

	body := fmt.Sprintf(
		"## Alert Details\n\n"+
			"* **Rule**: %s\n"+
			"* **Metric**: %s\n"+
			"* **Current Value**: %s\n"+
			"* **Baseline**: %s\n"+
			"* **Change**: %.1f%%\n"+
			"* **Severity**: %s\n"+
			"* **Owner**: %s\n\n"+
			"---\n"+
			"*Auto-generated by Olist Decision Engine v0.4*",
		ruleID, metric, current, baseline, change*100, severity, owner,
	)

	labels := a.BuildLabels(payload)

	return GitHubIssue{
		Title:  title,
		Body:   body,
		Labels: labels,
	}
}

// BuildComment formats a follow-up comment for a GitHub issue from a proposal.
func (a *GitHubAdapter) BuildComment(proposal action.ActionProposal) GitHubComment {
	payload := proposal.Payload
	proposalID := proposal.ProposalID
	caseID := proposal.CaseID
	actionType := proposal.ActionType
	severity := getString(payload, "severity", "medium")

	body := fmt.Sprintf(
		"**Follow-up on proposal `%s`**\n\n"+
			"* Case: `%s`\n"+
			"* Action Type: `%s`\n"+
			"* Severity: `%s`\n\n"+
			"This comment was auto-generated by the decision engine.",
		proposalID, caseID, actionType, severity,
	)

	return GitHubComment{Body: body}
}

// doRequest executes an HTTP request against the GitHub API.
func (a *GitHubAdapter) doRequest(method, path string, body interface{}) ([]byte, error) {
	url := a.baseURL + path

	var reqBody io.Reader
	if body != nil {
		jsonBytes, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewReader(jsonBytes)
	}

	req, err := http.NewRequest(method, url, reqBody)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+a.token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Content-Type", "application/json")

	resp, err := a.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	switch resp.StatusCode {
	case 200, 201:
		return respBody, nil
	case 401:
		return nil, fmt.Errorf("github api error: 401 unauthorized")
	case 403:
		return nil, fmt.Errorf("github api error: 403 forbidden (possible rate limit)")
	case 404:
		return nil, fmt.Errorf("github api error: 404 not found")
	case 422:
		return nil, fmt.Errorf("github api error: 422 validation failed: %s", string(respBody))
	default:
		return nil, fmt.Errorf("github api error: %d %s", resp.StatusCode, string(respBody))
	}
}

// CreateIssue creates a GitHub issue via the REST API and returns its URL.
func (a *GitHubAdapter) CreateIssue(ctx context.Context, issue GitHubIssue) (string, error) {
	if a.token == "" {
		return "", fmt.Errorf("github token not configured")
	}
	if a.config.Repo == "" {
		return "", fmt.Errorf("github repo not configured")
	}

	path := fmt.Sprintf("/repos/%s/issues", a.config.Repo)
	payload := map[string]interface{}{
		"title":  issue.Title,
		"body":   issue.Body,
		"labels": issue.Labels,
	}

	body, err := a.doRequest("POST", path, payload)
	if err != nil {
		return "", fmt.Errorf("create issue: %w", err)
	}

	var result struct {
		HTMLURL string `json:"html_url"`
		Number  int    `json:"number"`
	}
	if err := json.Unmarshal(body, &result); err != nil {
		return "", fmt.Errorf("failed to parse create issue response: %w", err)
	}

	log.Printf("[GitHubAdapter] CreateIssue: repo=%s issue=#%d url=%s",
		a.config.Repo, result.Number, result.HTMLURL)

	return result.HTMLURL, nil
}

// AddLabels adds labels to an existing GitHub issue.
func (a *GitHubAdapter) AddLabels(ctx context.Context, issueNumber int, labels []string) error {
	if a.token == "" {
		return fmt.Errorf("github token not configured")
	}
	if a.config.Repo == "" {
		return fmt.Errorf("github repo not configured")
	}

	path := fmt.Sprintf("/repos/%s/issues/%d/labels", a.config.Repo, issueNumber)
	payload := map[string]interface{}{
		"labels": labels,
	}

	_, err := a.doRequest("POST", path, payload)
	if err != nil {
		return fmt.Errorf("add labels: %w", err)
	}

	log.Printf("[GitHubAdapter] AddLabels: repo=%s issue=#%d labels=%v",
		a.config.Repo, issueNumber, labels)
	return nil
}

// AddComment adds a comment to an existing GitHub issue.
func (a *GitHubAdapter) AddComment(ctx context.Context, issueNumber int, comment GitHubComment) error {
	if a.token == "" {
		return fmt.Errorf("github token not configured")
	}
	if a.config.Repo == "" {
		return fmt.Errorf("github repo not configured")
	}

	path := fmt.Sprintf("/repos/%s/issues/%d/comments", a.config.Repo, issueNumber)
	payload := map[string]interface{}{
		"body": comment.Body,
	}

	_, err := a.doRequest("POST", path, payload)
	if err != nil {
		return fmt.Errorf("add comment: %w", err)
	}

	log.Printf("[GitHubAdapter] AddComment: repo=%s issue=#%d body_len=%d",
		a.config.Repo, issueNumber, len(comment.Body))
	return nil
}

// Execute implements action.ActionExecutor. In dry-run mode it builds the
// GitHub issue payload and returns it without making HTTP calls. Otherwise
// it creates a real GitHub issue and stores the URL in the dispatch payload.
func (a *GitHubAdapter) Execute(ctx context.Context, proposal action.ActionProposal, dryRun bool) (action.ExecutionResult, error) {
	issue := a.BuildIssue(proposal)

	payload := map[string]interface{}{
		"proposal_id": proposal.ProposalID,
		"case_id":     proposal.CaseID,
		"action_type": proposal.ActionType,
		"channel":     ActionChannel(proposal.ActionType),
		"dry_run":     dryRun,
		"issue": map[string]interface{}{
			"title":  issue.Title,
			"body":   issue.Body,
			"labels": issue.Labels,
		},
	}

	if dryRun {
		return action.ExecutionResult{
			Success:         true,
			DryRun:          true,
			DispatchPayload: payload,
		}, nil
	}

	if a.token == "" {
		return action.ExecutionResult{}, fmt.Errorf("github token not configured")
	}

	issueURL, err := a.CreateIssue(ctx, issue)
	if err != nil {
		return action.ExecutionResult{
			Success: false,
			Error:   err.Error(),
		}, nil
	}

	payload["issue_url"] = issueURL

	log.Printf("[GitHubAdapter] dispatched to repo %s: proposal_id=%s action_type=%s url=%s",
		a.config.Repo, proposal.ProposalID, proposal.ActionType, issueURL)

	return action.ExecutionResult{
		Success:         true,
		DryRun:          false,
		DispatchPayload: payload,
	}, nil
}

// Compile-time assertion that *GitHubAdapter satisfies action.ActionExecutor.
var _ action.ActionExecutor = (*GitHubAdapter)(nil)
