package adapter

import (
	"context"
	"fmt"
	"log"
	"strings"

	"baxi/internal/action"
)

// GitHubIssue represents the payload for creating or updating a GitHub issue.
type GitHubIssue struct {
	Title  string   `json:"title"`
	Body   string   `json:"body"`
	Labels []string `json:"labels,omitempty"`
}

// GitHubComment represents a comment to be added to a GitHub issue.
type GitHubComment struct {
	Body string `json:"body"`
}

// GitHubAdapter dispatches action proposals to GitHub (via API).
type GitHubAdapter struct {
	config GitHubConfig
}

// NewGitHubAdapter creates a new GitHubAdapter with the given config.
func NewGitHubAdapter(config GitHubConfig) *GitHubAdapter {
	return &GitHubAdapter{config: config}
}

// BuildLabels extracts label names from the proposal payload.
// It returns ["alert", severity, owner] matching the Python adapter.
func (a *GitHubAdapter) BuildLabels(payload map[string]interface{}) []string {
	severity := getString(payload, "severity", "medium")
	owner := getString(payload, "owner_role", "unassigned")

	labels := []string{"alert", severity, owner}

	// Deduplicate and filter empty strings
	seen := make(map[string]bool)
	result := make([]string, 0, len(labels))
	for _, label := range labels {
		label = strings.TrimSpace(label)
		if label != "" && !seen[label] {
			seen[label] = true
			result = append(result, label)
		}
	}
	return result
}

// BuildIssue formats an ActionProposal into a GitHubIssue payload.
// It mirrors the Python GitHubIssueAdapter.dry_run() behaviour.
func (a *GitHubAdapter) BuildIssue(proposal action.ActionProposal) GitHubIssue {
	payload := proposal.Payload

	ruleID := getString(payload, "rule_id", "unknown")
	metric := getString(payload, "metric_name", "metric")
	current := getString(payload, "current_value", "N/A")
	baseline := getString(payload, "baseline_value", "N/A")
	change := getFloat(payload, "change_rate", 0)
	severity := getString(payload, "severity", "medium")
	owner := getString(payload, "owner_role", "unassigned")

	title := fmt.Sprintf("[Alert] %s: %s anomaly detected", ruleID, metric)

	body := fmt.Sprintf(
		"## Alert Details\n\n"+
			"* **Rule**: %s\n"+
			"* **Metric**: %s\n"+
			"* **Current Value**: %s\n"+
			"* **Baseline**: %s\n"+
			"* **Change**: %.1f%%\n"+
			"* **Severity**: %s\n"+
			"* **Owner**: %s\n\n"+
			"---\n"+
			"*Auto-generated by Olist Decision Engine v0.4*",
		ruleID, metric, current, baseline, change*100, severity, owner,
	)

	labels := a.BuildLabels(payload)

	return GitHubIssue{
		Title:  title,
		Body:   body,
		Labels: labels,
	}
}

// BuildComment formats a follow-up comment for a GitHub issue from a proposal.
func (a *GitHubAdapter) BuildComment(proposal action.ActionProposal) GitHubComment {
	payload := proposal.Payload
	proposalID := proposal.ProposalID
	caseID := proposal.CaseID
	actionType := proposal.ActionType
	severity := getString(payload, "severity", "medium")

	body := fmt.Sprintf(
		"**Follow-up on proposal `%s`**\n\n"+
			"* Case: `%s`\n"+
			"* Action Type: `%s`\n"+
			"* Severity: `%s`\n\n"+
			"This comment was auto-generated by the decision engine.",
		proposalID, caseID, actionType, severity,
	)

	return GitHubComment{Body: body}
}

// CreateIssue is a stub for creating a GitHub issue via the REST API.
// In the current preview implementation it logs the intent and returns
// a synthetic issue URL without making an HTTP call.
func (a *GitHubAdapter) CreateIssue(ctx context.Context, issue GitHubIssue) (string, error) {
	if a.config.Token == "" {
		return "", fmt.Errorf("github token not configured")
	}
	if a.config.Repo == "" {
		return "", fmt.Errorf("github repo not configured")
	}
	log.Printf("[GitHubAdapter] CreateIssue: repo=%s title=%q labels=%v",
		a.config.Repo, issue.Title, issue.Labels)
	// Return a synthetic URL for dry-run / preview mode.
	return fmt.Sprintf("https://github.com/%s/issues/preview", a.config.Repo), nil
}

// AddLabels is a stub for adding labels to an existing GitHub issue.
func (a *GitHubAdapter) AddLabels(ctx context.Context, issueNumber int, labels []string) error {
	if a.config.Token == "" {
		return fmt.Errorf("github token not configured")
	}
	if a.config.Repo == "" {
		return fmt.Errorf("github repo not configured")
	}
	log.Printf("[GitHubAdapter] AddLabels: repo=%s issue=#%d labels=%v",
		a.config.Repo, issueNumber, labels)
	return nil
}

// AddComment is a stub for adding a comment to an existing GitHub issue.
func (a *GitHubAdapter) AddComment(ctx context.Context, issueNumber int, comment GitHubComment) error {
	if a.config.Token == "" {
		return fmt.Errorf("github token not configured")
	}
	if a.config.Repo == "" {
		return fmt.Errorf("github repo not configured")
	}
	log.Printf("[GitHubAdapter] AddComment: repo=%s issue=#%d body_len=%d",
		a.config.Repo, issueNumber, len(comment.Body))
	return nil
}

// Execute implements action.ActionExecutor. In dry-run mode it builds the
// GitHub issue payload and returns it without making HTTP calls. When the
// token is empty it returns an error. Otherwise it logs the dispatch and
// returns success with the issue payload embedded.
func (a *GitHubAdapter) Execute(ctx context.Context, proposal action.ActionProposal, dryRun bool) (action.ExecutionResult, error) {
	issue := a.BuildIssue(proposal)

	payload := map[string]interface{}{
		"proposal_id": proposal.ProposalID,
		"case_id":     proposal.CaseID,
		"action_type": proposal.ActionType,
		"channel":     ActionChannel(proposal.ActionType),
		"dry_run":     dryRun,
		"issue": map[string]interface{}{
			"title":  issue.Title,
			"body":   issue.Body,
			"labels": issue.Labels,
		},
	}

	if dryRun {
		return action.ExecutionResult{
			Success:         true,
			DryRun:          true,
			DispatchPayload: payload,
		}, nil
	}

	if a.config.Token == "" {
		return action.ExecutionResult{}, fmt.Errorf("github token not configured")
	}

	log.Printf("[GitHubAdapter] dispatching to repo %s: proposal_id=%s action_type=%s title=%q",
		a.config.Repo, proposal.ProposalID, proposal.ActionType, proposal.Title)

	return action.ExecutionResult{
		Success:         true,
		DryRun:          false,
		DispatchPayload: payload,
	}, nil
}

// Compile-time assertion that *GitHubAdapter satisfies action.ActionExecutor.
var _ action.ActionExecutor = (*GitHubAdapter)(nil)
