-- +goose Up
-- +goose StatementBegin

-- ops.metric_alert: Anomaly alerts generated by rule engine
-- Mapped from SQLite alert_events (36 rows)
CREATE TABLE ops.metric_alert (
    alert_id        TEXT PRIMARY KEY,
    rule_id         TEXT NOT NULL,
    event_date      DATE NOT NULL,
    severity        TEXT NOT NULL,
    metric_name     TEXT NOT NULL,
    object_type     TEXT DEFAULT 'global',
    object_id       TEXT DEFAULT 'global',
    current_value   NUMERIC(18,4),
    baseline_value  NUMERIC(18,4),
    change_rate     NUMERIC(10,6),
    sample_size     BIGINT,
    affected_orders BIGINT,
    affected_gmv    NUMERIC(18,2),
    impact_score    NUMERIC(10,6),
    evidence_json   JSONB,
    description     TEXT,
    owner_role      TEXT,
    status          TEXT DEFAULT 'new',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE ops.metric_alert IS 'Anomaly alerts from metric monitoring (mapped from alert_events)';
COMMENT ON COLUMN ops.metric_alert.alert_id IS 'Renamed from SQLite event_id for clarity';

-- ops.recommendation: Strategic recommendations from heuristic/LLM
-- Mapped from SQLite strategy_recommendations (36 rows)
CREATE TABLE ops.recommendation (
    recommendation_id   TEXT PRIMARY KEY,
    alert_id            TEXT,
    decision_source     TEXT NOT NULL DEFAULT 'heuristic',
    rule_id             TEXT,
    strategy_title      TEXT NOT NULL,
    strategy_detail     TEXT,
    target_object_type  TEXT,
    target_object_id    TEXT,
    expected_impact     TEXT,
    risk_level          TEXT,
    confidence          TEXT,
    requires_approval   BOOLEAN DEFAULT FALSE,
    approval_status     TEXT DEFAULT 'draft',
    execution_status    TEXT DEFAULT 'draft',
    owner_role          TEXT,
    success_metric      TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE ops.recommendation IS 'Strategic recommendations (mapped from strategy_recommendations)';
COMMENT ON COLUMN ops.recommendation.alert_id IS 'Renamed from SQLite event_id for clarity';

-- ops.task: Action items assigned to roles/users
-- Mapped from SQLite action_tasks (36 rows)
CREATE TABLE ops.task (
    task_id             TEXT PRIMARY KEY,
    recommendation_id   TEXT,
    alert_id            TEXT,
    task_title          TEXT NOT NULL,
    task_description    TEXT,
    target_object_type  TEXT,
    target_object_id    TEXT,
    task_source         TEXT DEFAULT 'heuristic_strategy',
    owner_role          TEXT,
    owner_user_id       TEXT,
    priority            TEXT DEFAULT 'medium',
    due_at              TIMESTAMPTZ,
    status              TEXT DEFAULT 'todo',
    feedback            TEXT,
    completed_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (recommendation_id) REFERENCES ops.recommendation(recommendation_id) ON DELETE SET NULL
);

COMMENT ON TABLE ops.task IS 'Action tasks assigned to roles (mapped from action_tasks)';
COMMENT ON COLUMN ops.task.alert_id IS 'Renamed from SQLite event_id for clarity';

-- ops.outbox_event: Outbound dispatch queue (Outbox pattern)
-- Mapped from SQLite event_outbox (36 rows)
CREATE TABLE ops.outbox_event (
    event_id            TEXT PRIMARY KEY,
    event_type          TEXT NOT NULL,
    source_type         TEXT NOT NULL,
    source_id           TEXT NOT NULL,
    payload_json        JSONB NOT NULL,
    target_channel      TEXT NOT NULL,
    status              TEXT DEFAULT 'pending',
    dispatch_attempts   BIGINT DEFAULT 0,
    last_dispatch_at    TIMESTAMPTZ,
    external_ref        TEXT,
    adapter_name        TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at        TIMESTAMPTZ,
    error_message       TEXT
);

COMMENT ON TABLE ops.outbox_event IS 'Outbound dispatch queue (mapped from event_outbox)';
COMMENT ON COLUMN ops.outbox_event.event_id IS 'Renamed from SQLite outbox_id for consistency';

-- ops.dispatch_attempt: Per-attempt dispatch tracking (NEW table)
CREATE TABLE ops.dispatch_attempt (
    attempt_id      BIGSERIAL PRIMARY KEY,
    event_id        TEXT NOT NULL,
    attempt_number  BIGINT,
    status          TEXT,
    dispatched_at   TIMESTAMPTZ,
    response_json   JSONB,
    error_message   TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE ops.dispatch_attempt IS 'Per-attempt outbox dispatch tracking';

-- ops.qoder_job: External Qoder agent job tracking
-- Mapped from SQLite qoder_jobs (0 rows)
CREATE TABLE ops.qoder_job (
    job_id              TEXT PRIMARY KEY,
    trigger_event_id    TEXT,
    job_type            TEXT NOT NULL,
    job_title           TEXT NOT NULL,
    job_context_json    JSONB,
    dispatch_channel    TEXT NOT NULL,
    dispatch_status     TEXT DEFAULT 'pending',
    external_ref        TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    dispatched_at       TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    FOREIGN KEY (trigger_event_id) REFERENCES ops.metric_alert(alert_id) ON DELETE SET NULL
);

COMMENT ON TABLE ops.qoder_job IS 'Qoder agent job tracking (mapped from qoder_jobs)';

-- ops.review_retro: Post-execution retrospection records
-- Mapped from SQLite review_retro (0 rows)
CREATE TABLE ops.review_retro (
    review_id           TEXT PRIMARY KEY,
    recommendation_id   TEXT,
    task_id             TEXT,
    review_type         TEXT DEFAULT 'simulated',
    review_source       TEXT DEFAULT 'hindsight_rule',
    actual_result       TEXT,
    actual_impact       TEXT,
    is_effective        BOOLEAN,
    lesson_learned      TEXT,
    promote_to_rule     BOOLEAN DEFAULT FALSE,
    status              TEXT DEFAULT 'draft',
    feedback            TEXT,
    reviewed_at         TIMESTAMPTZ,
    FOREIGN KEY (recommendation_id) REFERENCES ops.recommendation(recommendation_id) ON DELETE SET NULL
);

COMMENT ON TABLE ops.review_retro IS 'Post-execution review and retrospection (mapped from review_retro)';

-- Indexes for operational query performance
CREATE INDEX idx_ops_metric_alert_status_severity ON ops.metric_alert(status, severity, created_at);
CREATE INDEX idx_ops_metric_alert_object ON ops.metric_alert(object_type, object_id);
CREATE INDEX idx_ops_task_status_owner ON ops.task(status, owner_role, priority);
CREATE INDEX idx_ops_outbox_event_status ON ops.outbox_event(status);
CREATE INDEX idx_ops_outbox_event_created ON ops.outbox_event(created_at);
CREATE INDEX idx_ops_dispatch_attempt_event ON ops.dispatch_attempt(event_id);
CREATE INDEX idx_ops_qoder_job_status ON ops.qoder_job(dispatch_status, created_at);
CREATE INDEX idx_ops_review_retro_recommendation ON ops.review_retro(recommendation_id);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS ops.review_retro CASCADE;
DROP TABLE IF EXISTS ops.qoder_job CASCADE;
DROP TABLE IF EXISTS ops.dispatch_attempt CASCADE;
DROP TABLE IF EXISTS ops.outbox_event CASCADE;
DROP TABLE IF EXISTS ops.task CASCADE;
DROP TABLE IF EXISTS ops.recommendation CASCADE;
DROP TABLE IF EXISTS ops.metric_alert CASCADE;

-- +goose StatementEnd
