export const meta = {
  name: 'baxi-p0-fix',
  description: 'Fix all 6 P0 critical issues from the Baxi audit (JWT, SQL injection, decision engine, frontend, Docker)',
  phases: [
    { title: 'Fix', detail: '6 parallel agents fixing all P0 issues' },
    { title: 'Verify', detail: 'Run all tests and build checks' },
    { title: 'Report', detail: 'Synthesize fix report' },
  ],
}

// === Phase 1: Parallel P0 fixes ===
phase('Fix')

const FIX_TASKS = [
  // Agent 1: JWT (Opus - heavy architectural change)
  {
    label: 'JWT Signature Verification',
    model: 'opus',
    prompt: [
      'Fix the JWT authentication vulnerability in the Baxi project at /home/zzz/project/baxi.',
      '',
      '## Problem',
      'The JWT authentication in `internal/api/middleware/identity.go` has critical security flaws:',
      '1. `parseJWTClaims` (line 88-105) only base64-decodes the payload, NEVER verifies the signature (parts[2])',
      '2. `legacyIdentity()` (line 24-30) grants admin role to any unparseable token',
      '3. `extractIdentity` (line 55-84) falls back to legacy admin on any parse failure',
      '',
      '## Fix Instructions',
      '',
      '### Step 1: Add dependency',
      '```bash',
      'cd /home/zzz/project/baxi && go get github.com/golang-jwt/jwt/v5',
      '```',
      '',
      '### Step 2: Modify `internal/api/middleware/identity.go`',
      '',
      '**Replace** the import block to add:',
      '```go',
      '"github.com/golang-jwt/jwt/v5"',
      '```',
      '',
      '**Downgrade legacyIdentity()** - change admin to viewer:',
      '```go',
      'func legacyIdentity() *UserIdentity {',
      '    return &UserIdentity{',
      '        UserID:   "qoder",',
      '        Username: "qoder",',
      '        Roles:    []string{"viewer"},',
      '    }',
      '}',
      '```',
      '',
      '**Add a package-level JWT secret setter** (the secret will be set during server init):',
      '```go',
      'var jwtSecret []byte',
      '',
      '// SetJWTSecret configures the HMAC key used for JWT verification.',
      '// Must be called during server initialization before processing requests.',
      'func SetJWTSecret(secret []byte) {',
      '    jwtSecret = secret',
      '}',
      '```',
      '',
      '**Rewrite parseJWTClaims** to use golang-jwt with signature verification:',
      '```go',
      'func parseJWTClaims(token string) (*jwtClaims, error) {',
      '    if len(jwtSecret) == 0 {',
      '        return nil, fmt.Errorf("JWT secret not configured")',
      '    }',
      '',
      '    parser := jwt.NewParser(jwt.WithValidMethods([]string{"HS256"}))',
      '    parsed, err := parser.Parse(token, func(t *jwt.Token) (interface{}, error) {',
      '        return jwtSecret, nil',
      '    })',
      '    if err != nil {',
      '        return nil, err',
      '    }',
      '',
      '    claims, ok := parsed.Claims.(jwt.MapClaims)',
      '    if !ok || !parsed.Valid {',
      '        return nil, fmt.Errorf("invalid token claims")',
      '    }',
      '',
      '    result := &jwtClaims{}',
      '    if sub, ok := claims["sub"].(string); ok {',
      '        result.Sub = sub',
      '    }',
      '    if name, ok := claims["name"].(string); ok {',
      '        result.Name = name',
      '    }',
      '    if email, ok := claims["email"].(string); ok {',
      '        result.Email = email',
      '    }',
      '    if roles, ok := claims["roles"].([]interface{}); ok {',
      '        for _, r := range roles {',
      '            if s, ok := r.(string); ok {',
      '                result.Roles = append(result.Roles, s)',
      '            }',
      '        }',
      '    }',
      '',
      '    return result, nil',
      '}',
      '```',
      '',
      '**Add the fmt import** if not already present.',
      '',
      '### Step 3: Wire up the secret in server initialization',
      'In `internal/api/server.go` (or wherever the server is created), call:',
      '```go',
      'middleware.SetJWTSecret([]byte(cfg.APIToken))',
      '```',
      'Where cfg.APIToken is the existing bearer token from config. Find the config struct in `internal/config/`.',
      '',
      '### Step 4: Update tests in `internal/api/middleware/auth_test.go`',
      'Add tests for:',
      '- Valid HS256-signed JWT passes verification',
      '- Tampered JWT signature is rejected',
      '- Expired JWT is rejected',
      '- Non-JWT legacy token gets viewer role (not admin)',
      '- Missing JWT secret returns error',
      '',
      '### Important',
      '- Do NOT change GetIdentity fallback behavior (it still returns legacy identity, which is now viewer)',
      '- Do NOT change extractIdentity control flow (it still falls back to legacy, which is now viewer)',
      '- Keep the existing BearerTokenActorKey and IdentityKey context keys unchanged',
      '- Make sure go build ./... passes after all changes',
    ].join('\n'),
  },

  // Agent 2: SQL Injection (Sonnet)
  {
    label: 'SQL Injection Fix',
    model: 'sonnet',
    prompt: [
      'Fix SQL injection vulnerabilities in the Baxi project at /home/zzz/project/baxi.',
      '',
      '## Fix 1: CountTableRows',
      'File: `internal/repository/governance/repository.go`, lines 102-113',
      '',
      'Current code uses fmt.Sprintf to interpolate schema and table names directly into SQL.',
      '',
      '**Replace line 105:**',
      '```go',
      'query := fmt.Sprintf(`SELECT COUNT(*) FROM %s.%s`, schema, table)',
      '```',
      '**With:**',
      '```go',
      'query := fmt.Sprintf(`SELECT COUNT(*) FROM %s`, pgx.Identifier{schema, table}.Sanitize())',
      '```',
      '',
      'Make sure `pgx/v5` is imported (check the file existing imports).',
      '',
      '## Fix 2: sanitizeIdent',
      'File: `internal/repository/ontology/repository.go`, lines 506-511',
      '',
      'Current code wraps in double quotes but does NOT escape embedded double quotes.',
      '',
      '**Replace the entire sanitizeIdent function:**',
      '```go',
      'func sanitizeIdent(ident string) string {',
      '    return pgx.Identifier{ident}.Sanitize()',
      '}',
      '```',
      '',
      'pgx is already imported in this file (line 10: "github.com/jackc/pgx/v5").',
      '',
      '## Verification',
      'After making changes:',
      '1. Run: cd /home/zzz/project/baxi && go build ./...',
      '2. Run: cd /home/zzz/project/baxi && go test ./internal/repository/... -count=1 -v',
      '',
      'Do NOT modify any other code in these files. Only change the specific SQL injection points.',
    ].join('\n'),
  },

  // Agent 3: Decision Engine Fix (Sonnet)
  {
    label: 'Decision Engine Fix',
    model: 'sonnet',
    prompt: [
      'Fix two bugs in the Baxi decision engine at /home/zzz/project/baxi.',
      '',
      '## Bug 1: escalate_to_human missing from validActions',
      'File: `internal/llm/schema_validator.go`, lines 101-106',
      '',
      'The validActions map is missing ActionTypeEscalateToHuman. Add it:',
      '',
      '```go',
      'validActions := map[string]bool{',
      '    ActionTypeCreateFollowupTask:  true,',
      '    ActionTypeNotifyOwner:         true,',
      '    ActionTypeExportReport:        true,',
      '    ActionTypeCreateOutboxMessage: true,',
      '    ActionTypeEscalateToHuman:     true,',
      '}',
      '```',
      '',
      '## Bug 2: buildRepairContext drops validation errors',
      '### Step A: Add RepairErrors field to GovernanceInfo',
      'File: `internal/llm/provider.go`, lines 38-44',
      '',
      'Add a new field to the GovernanceInfo struct:',
      '',
      '```go',
      'type GovernanceInfo struct {',
      '    Classification   string   `json:"classification"`',
      '    RedactionApplied bool     `json:"redaction_applied"`',
      '    RedactedFields   []string `json:"redacted_fields"`',
      '    Role             string   `json:"role"`',
      '    RepairErrors     []string `json:"repair_errors,omitempty"`',
      '}',
      '```',
      '',
      '### Step B: Inject errors in buildRepairContext',
      'File: `internal/decision/engine.go`, lines 386-398',
      '',
      'After computing errMsgs, assign them to the repaired context:',
      '',
      'Replace the buildRepairContext function body so that after computing errMsgs and setting the role, add:',
      'repaired.GovernanceInfo.RepairErrors = errMsgs',
      '',
      'The full function should be:',
      '```go',
      'func (e *DecisionEngine) buildRepairContext(original llm.LLMSafeContext, validationErrors []llm.ValidationError) llm.LLMSafeContext {',
      '    errMsgs := make([]string, len(validationErrors))',
      '    for i, verr := range validationErrors {',
      '        errMsgs[i] = verr.Field + ": " + verr.Message',
      '    }',
      '    repaired := original',
      '    if repaired.GovernanceInfo.Role == "" {',
      '        repaired.GovernanceInfo.Role = "agent_readonly"',
      '    }',
      '    repaired.GovernanceInfo.RepairErrors = errMsgs',
      '    return repaired',
      '}',
      '```',
      '',
      '## Verification',
      'Run: cd /home/zzz/project/baxi && go test ./internal/llm/... ./internal/decision/... -count=1 -v',
      '',
      'Do NOT change any other code in these files.',
    ].join('\n'),
  },

  // Agent 4: Frontend Types (Sonnet)
  {
    label: 'Frontend Types Fix',
    model: 'sonnet',
    prompt: [
      'Add missing TypeScript type definitions to the Baxi frontend at /home/zzz/project/baxi/frontend.',
      '',
      'File: frontend/src/api/types.ts',
      '',
      'Read the file first, then add these interfaces at the end of the file:',
      '',
      '```typescript',
      'export interface PolicyResults {',
      '  human_approval_required: boolean',
      '  allowed_actions: string[]',
      '  blocked_actions: string[]',
      '  risk_levels: Record<string, string>',
      '  requires_approval_actions: string[]',
      '  evidence_sources: string[]',
      '}',
      '',
      'export interface DecisionCaseResponse {',
      '  decision_case_id: string',
      '  status: string',
      '  object_type: string',
      '  object_id: string',
      '  source_type: string',
      '  source_id: string',
      '  severity: string',
      '  context_hash: string',
      '  created_at: string',
      '  updated_at: string',
      '  policy_results: PolicyResults',
      '}',
      '',
      'export interface GovernanceStatusResponse {',
      '  overall_health: string',
      '  version: string',
      '  configs: Record<string, string>',
      '}',
      '```',
      '',
      '## Verification',
      'Run: cd /home/zzz/project/baxi/frontend && npx tsc --noEmit',
      '',
      'If tsc reports any additional missing types in CaseDetail.tsx or PolicyInspector.tsx, add those too.',
    ].join('\n'),
  },

  // Agent 5: Docker Hardening (Sonnet)
  {
    label: 'Docker Security',
    model: 'sonnet',
    prompt: [
      'Harden Docker configuration for the Baxi project at /home/zzz/project/baxi.',
      '',
      '## Fix 1: Dockerfile.api',
      'After the FROM alpine:latest line, add a non-root user:',
      '```dockerfile',
      'RUN adduser -D -s /bin/sh appuser',
      '```',
      'Before the ENTRYPOINT line, add:',
      '```dockerfile',
      'USER appuser',
      '```',
      '',
      '## Fix 2: Dockerfile.worker',
      'Same changes as Dockerfile.api - add user after FROM alpine, USER before ENTRYPOINT.',
      '',
      '## Fix 3: docker-compose.yml',
      'Change the PostgreSQL port mapping from:',
      '  - "5432:5432"',
      'To:',
      '  - "127.0.0.1:5432:5432"',
      '',
      'This restricts PostgreSQL to localhost only.',
      '',
      'Read each file first to understand the exact structure before making changes.',
    ].join('\n'),
  },
]

const fixResults = await parallel(
  FIX_TASKS.map(t => () =>
    agent(t.prompt, { label: t.label, phase: 'Fix', model: t.model })
  )
)

log('Phase 1 complete: ' + (fixResults?.filter(Boolean).length || 0) + ' agents finished')

// === Phase 2: Verify ===
phase('Verify')

const verifyResults = await parallel([
  () => agent(
    [
      'Run the full Go test suite and build verification for the Baxi project at /home/zzz/project/baxi.',
      '',
      'Execute these commands and report results:',
      '1. cd /home/zzz/project/baxi && go mod tidy 2>&1',
      '2. cd /home/zzz/project/baxi && go build ./... 2>&1',
      '3. cd /home/zzz/project/baxi && go vet ./... 2>&1',
      '4. cd /home/zzz/project/baxi && go test ./... -count=1 2>&1',
      '',
      'If any step fails, report the exact error message and which file/line caused it.',
      '',
      'Report: build_ok (bool), vet_ok (bool), tests_passed (int), tests_failed (int), failures (list of test name + error).',
    ].join('\n'),
    { label: 'Go Verification', phase: 'Verify', model: 'sonnet',
      schema: {
        type: 'object',
        properties: {
          build_ok: { type: 'boolean' },
          vet_ok: { type: 'boolean' },
          tests_passed: { type: 'number' },
          tests_failed: { type: 'number' },
          failures: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                test: { type: 'string' },
                error: { type: 'string' }
              }
            }
          },
          summary: { type: 'string' }
        },
        required: ['build_ok', 'vet_ok', 'tests_passed', 'tests_failed', 'summary']
      }
    }
  ),
  () => agent(
    [
      'Run frontend verification for the Baxi project at /home/zzz/project/baxi/frontend.',
      '',
      'Execute these commands:',
      '1. cd /home/zzz/project/baxi/frontend && npm test -- --run 2>&1',
      '2. cd /home/zzz/project/baxi/frontend && npx tsc --noEmit 2>&1',
      '',
      'Report: tests_passed (int), tests_failed (int), tsc_ok (bool), errors (list).',
    ].join('\n'),
    { label: 'Frontend Verification', phase: 'Verify', model: 'haiku',
      schema: {
        type: 'object',
        properties: {
          tests_passed: { type: 'number' },
          tests_failed: { type: 'number' },
          tsc_ok: { type: 'boolean' },
          errors: { type: 'array', items: { type: 'string' } },
          summary: { type: 'string' }
        },
        required: ['tests_passed', 'tests_failed', 'tsc_ok', 'summary']
      }
    }
  )
])

// === Phase 3: Report ===
phase('Report')

const goV = verifyResults?.[0] || {}
const feV = verifyResults?.[1] || {}

const report = await agent(
  [
    'Generate a concise fix report for the Baxi P0 fixes.',
    '',
    '## Fix Summary:',
    '- 5 parallel fix agents executed',
    '- Agent 1 (Opus): JWT signature verification + legacy identity downgrade',
    '- Agent 2 (Sonnet): SQL injection fixes in CountTableRows and sanitizeIdent',
    '- Agent 3 (Sonnet): Decision engine - escalate_to_human + buildRepairContext',
    '- Agent 4 (Sonnet): Frontend missing TypeScript types',
    '- Agent 5 (Sonnet): Docker security hardening',
    '',
    '## Verification Results:',
    '- Go: build=' + goV.build_ok + ', vet=' + goV.vet_ok + ', passed=' + goV.tests_passed + ', failed=' + goV.tests_failed,
    '- Frontend: passed=' + feV.tests_passed + ', tsc=' + feV.tsc_ok,
    '',
    'Write a concise report in Chinese covering:',
    '1. Summary of all changes made (files modified)',
    '2. Test results',
    '3. Any remaining issues or warnings',
    '4. Next steps (P1 items)',
  ].join('\n'),
  { label: 'Fix Report', phase: 'Report', model: 'sonnet' }
)

return {
  fixes: fixResults?.filter(Boolean).length || 0,
  verification: {
    go: verifyResults?.[0],
    frontend: verifyResults?.[1]
  },
  report: report
}
