export const meta = {
  name: 'baxi-p1-fix',
  description: 'Fix all P1 bugs from Baxi audit (access control, redaction, stubs, routes, timeout, error format, transactions)',
  phases: [
    { title: 'Fix', detail: '5 parallel agents fixing all P1 bugs' },
    { title: 'Verify', detail: 'Run all tests and build checks' },
    { title: 'Report', detail: 'Synthesize fix report' },
  ],
}

// === Phase 1: Parallel P1 fixes ===
phase('Fix')

const FIX_TASKS = [
  // Agent 1: GitHub Adapter (Opus - complex HTTP integration)
  {
    label: 'GitHub Adapter',
    model: 'opus',
    prompt: [
      'Replace the GitHub adapter stub with real GitHub API calls in the Baxi project at /home/zzz/project/baxi.',
      '',
      'File: internal/adapter/github.go',
      '',
      '## Current State',
      'All methods (CreateIssue, AddLabels, AddComment, Execute) are stubs returning fake data.',
      '',
      '## Fix Instructions',
      '',
      '### Step 1: Add fields to GitHubAdapter struct',
      'Add httpClient *http.Client and token string fields to the GitHubAdapter struct.',
      'Also add a baseURL field (default: "https://api.github.com") for testability.',
      '',
      '### Step 2: Implement CreateIssue',
      'POST to /repos/{owner}/{repo}/issues with:',
      '- Authorization: Bearer {token} header',
      '- JSON body: {"title": issue.Title, "body": issue.Body, "labels": issue.Labels}',
      '- Parse response to get the real issue number and html_url',
      '- Return the real html_url',
      '',
      '### Step 3: Implement AddLabels',
      'POST to /repos/{owner}/{repo}/issues/{number}/labels',
      '- JSON body: {"labels": ["label1", "label2"]}',
      '',
      '### Step 4: Implement AddComment',
      'POST to /repos/{owner}/{repo}/issues/{number}/comments',
      '- JSON body: {"body": comment.Body}',
      '',
      '### Step 5: Update Execute',
      'In non-dryRun mode, call CreateIssue to get the real URL.',
      'Store the returned URL in DispatchPayload.',
      'Keep dryRun mode as-is (returns success without API call).',
      '',
      '### Step 6: Add helper method',
      'Add a doRequest(method, path string, body interface{}) ([]byte, error) helper that:',
      '- Constructs the full URL from baseURL + path',
      '- Sets Authorization, Accept, Content-Type headers',
      '- Handles common error codes (401, 403, 404, 422)',
      '- Returns the response body',
      '',
      '### Reference Pattern',
      'Look at internal/adapter/feishu_client.go for the HTTP client pattern used in this project.',
      '',
      '### Testing',
      'Create or update internal/adapter/github_test.go:',
      '- Use httptest.NewServer to mock the GitHub API',
      '- Test CreateIssue returns real URL from mock',
      '- Test AddLabels sends correct payload',
      '- Test AddComment sends correct payload',
      '- Test Execute dry-run mode does not call API',
      '- Test Execute non-dry-run calls CreateIssue',
      '- Test error handling (401, 404, rate limit)',
      '',
      '## Verification',
      'Run: cd /home/zzz/project/baxi && go test ./internal/adapter/... -count=1 -v',
      'Run: cd /home/zzz/project/baxi && go build ./...',
    ].join('\n'),
  },

  // Agent 2: Access Control + Redaction (Sonnet)
  {
    label: 'Access Control & Redaction',
    model: 'sonnet',
    prompt: [
      'Fix 4 access control and redaction bugs in the Baxi project at /home/zzz/project/baxi.',
      '',
      '## Bug A: JSONB Conditions Check',
      'File: internal/governance/access_policy.go, around line 52-54',
      '',
      'Current code uses len(p.ConditionsJSONB) > 4 which is a fragile byte-length heuristic.',
      'Replace with proper JSON parsing:',
      '',
      '```go',
      'if p.ConditionsJSONB != nil {',
      '    var conditions map[string]interface{}',
      '    if err := json.Unmarshal(p.ConditionsJSONB, &conditions); err == nil && len(conditions) > 0 {',
      '        return model.AccessConditional',
      '    }',
      '}',
      '```',
      '',
      'Make sure "encoding/json" is imported.',
      '',
      '## Bug B: Deny-Overrides Policy',
      'File: internal/governance/access_policy.go, around line 42-56',
      '',
      'Current CheckAccess only checks allow policies, skipping deny with continue.',
      'Implement deny-overrides: first scan for deny matches, then allow matches.',
      '',
      'Replace the single loop with two phases:',
      'Phase 1: Loop through policies, check Effect=="deny", match resource+action, return AccessDenied if matched.',
      'Phase 2: Loop through policies, check Effect=="allow", match resource+action, check conditions, return AccessAllowed if matched.',
      'Default: return AccessDenied.',
      '',
      'Read the current function first to understand the exact structure before modifying.',
      '',
      '## Bug C: shouldRedact Vocabulary Mismatch',
      'File: internal/ontology/context_builder.go, around line 119-131',
      '',
      'Current shouldRedact compares against "pii", "sensitive", "derived_sensitive" strings.',
      'But the ontology uses L0-L4 codes. Rewrite to use numeric levels:',
      '',
      '```go',
      'func sensitivityLevel(s string) int {',
      '    if len(s) == 2 && s[0] == \'L\' && s[1] >= \'0\' && s[1] <= \'4\' {',
      '        return int(s[1] - \'0\')',
      '    }',
      '    return -1',
      '}',
      '',
      'func shouldRedact(role, sensitivity string) bool {',
      '    level := sensitivityLevel(sensitivity)',
      '    if level < 0 {',
      '        return false',
      '    }',
      '    switch role {',
      '    case "admin":',
      '        return false',
      '    case "analyst":',
      '        return level >= 3',
      '    case "viewer", "agent_readonly", "":',
      '        return level >= 2',
      '    default:',
      '        return level >= 2',
      '    }',
      '}',
      '```',
      '',
      '## Bug D: queryLogs Silent Error Swallowing',
      'File: internal/repository/log/repository.go, around line 153-156',
      '',
      'Replace:',
      '  return []LogRow{}, 0, nil',
      'With:',
      '  return nil, 0, fmt.Errorf("query logs: %w", err)',
      '',
      '## Verification',
      'Run: cd /home/zzz/project/baxi && go test ./internal/governance/... ./internal/ontology/... ./internal/repository/... -count=1 -v',
      'Run: cd /home/zzz/project/baxi && go build ./...',
    ].join('\n'),
  },

  // Agent 3: Infrastructure Fixes (Sonnet)
  {
    label: 'Infrastructure Fixes',
    model: 'sonnet',
    prompt: [
      'Fix 3 infrastructure issues in the Baxi project at /home/zzz/project/baxi.',
      '',
      '## Bug A: Pipeline Timeout Protection',
      'File: internal/pipeline/runner.go',
      '',
      'The Run method has no timeout. Add at the beginning of the Run function:',
      '```go',
      'ctx, cancel := context.WithTimeout(ctx, 30*time.Minute)',
      'defer cancel()',
      '```',
      'Add "time" to the import block if not already present.',
      '',
      '## Bug B: Config Sync Transaction Boundary',
      'Files: internal/configloader/loader.go + internal/configloader/snapshot.go',
      '',
      'In loader.go, wrap the 5 sync calls in SyncSnapshots with a transaction:',
      '1. Add tx, err := cl.pool.Begin(ctx) + defer tx.Rollback(ctx) at the start',
      '2. Pass tx instead of cl.pool to each sync function',
      '3. Add tx.Commit(ctx) at the end',
      '',
      'In snapshot.go, change the 5 sync function signatures from:',
      '  func syncXxx(ctx context.Context, pool *pgxpool.Pool, registry *ConfigRegistry) error',
      'To:',
      '  func syncXxx(ctx context.Context, tx pgx.Tx, registry *ConfigRegistry) error',
      '',
      'And change all pool.Exec(ctx, ...) calls inside them to tx.Exec(ctx, ...).',
      'pgx.Tx has the same Exec method signature as pgxpool.Pool.',
      '',
      'Make sure pgx is imported: "github.com/jackc/pgx/v5"',
      '',
      '## Bug C: MCP Pipeline Runner Stub',
      'File: cmd/baxi-mcp/main.go, around line 116-122',
      '',
      'The pipelineRunService.Run method is a stub that returns ("run-id", nil).',
      '',
      'Fix: delegate to the real pipeline.Runner:',
      '```go',
      'func (s *pipelineRunService) Run(ctx context.Context, config string) (string, error) {',
      '    input := pipeline.RunInput{',
      '        RunType: "full",',
      '        Mode:    "mcp",',
      '        DataDir: "./data/raw",',
      '    }',
      '    if config != "" {',
      '        input.RunType = config',
      '    }',
      '    err := s.runner.Run(ctx, input)',
      '    if err != nil {',
      '        return "", err',
      '    }',
      '    return "pipeline-run-" + input.RunType, nil',
      '}',
      '```',
      '',
      'NOTE: If Runner.Run currently returns only error, you do NOT need to change its signature.',
      'Just call it and return a correlation ID string on success.',
      '',
      '## Verification',
      'Run: cd /home/zzz/project/baxi && go build ./...',
      'Run: cd /home/zzz/project/baxi && go test ./internal/pipeline/... ./internal/configloader/... -count=1 -v',
    ].join('\n'),
  },

  // Agent 4: Frontend Routes + Handler Cache (Sonnet)
  {
    label: 'Routes & Handler Cache',
    model: 'sonnet',
    prompt: [
      'Fix frontend routing and handler factory caching in the Baxi project at /home/zzz/project/baxi.',
      '',
      '## Bug A: Frontend Missing Routes',
      'File: frontend/src/App.tsx',
      '',
      'Three pages exist but have no route registration:',
      '- CaseDetail.tsx (uses useParams for :id)',
      '- AuditTimeline.tsx',
      '- PolicyInspector.tsx',
      '',
      'Read App.tsx first, then:',
      '1. Add imports after the existing import block:',
      '   import CaseDetail from "./pages/CaseDetail"',
      '   import AuditTimeline from "./pages/AuditTimeline"',
      '   import PolicyInspector from "./pages/PolicyInspector"',
      '',
      '2. Add routes BEFORE the catch-all <Route path="*"> line:',
      '   <Route path="/cases/:id" element={<CaseDetail />} />',
      '   <Route path="/audit-timeline" element={<AuditTimeline />} />',
      '   <Route path="/policy-inspector" element={<PolicyInspector />} />',
      '',
      '## Bug B: Handler Factory Caching',
      'Files: internal/api/server.go + internal/api/handler_factories.go',
      '',
      'Currently 5 handler factories are cached (llm, feishu, diagnosis, decision, action)',
      'but 9 are NOT cached (outbox, governance, qoder, status, log, agentLog, alert, review, pipeline).',
      '',
      'In server.go, add 9 cached fields to the Server struct:',
      '  outboxHandlerVal     *handler.OutboxHandler',
      '  governanceHandlerVal *handler.GovernanceHandler',
      '  qoderHandlerVal      *handler.QoderHandler',
      '  statusHandlerVal     *handler.StatusHandler',
      '  logHandlerVal        *handler.LogHandler',
      '  agentLogHandlerVal   *handler.AgentLogHandler',
      '  alertHandlerVal      *handler.AlertHandler',
      '  reviewHandlerVal     *handler.ReviewHandler',
      '  pipelineHandlerVal   *handler.PipelineHandler',
      '',
      'In handler_factories.go, wrap each uncached factory in a nil-check pattern:',
      '  func (s *Server) outboxHandler() *handler.OutboxHandler {',
      '      if s.outboxHandlerVal == nil {',
      '          // existing initialization code',
      '          s.outboxHandlerVal = ...',
      '      }',
      '      return s.outboxHandlerVal',
      '  }',
      '',
      'Follow the exact pattern of llmHandler() or feishuHandler() already in the file.',
      '',
      '## Verification',
      'Run: cd /home/zzz/project/baxi && go build ./...',
      'Run: cd /home/zzz/project/baxi && go test ./internal/api/... -count=1 -v',
      'Run: cd /home/zzz/project/baxi/frontend && npm test -- --run',
    ].join('\n'),
  },

  // Agent 5: Error Response Unification (Sonnet - mechanical, high volume)
  {
    label: 'Error Format Unification',
    model: 'sonnet',
    prompt: [
      'Unify all API error responses in the Baxi project at /home/zzz/project/baxi to use the structured format.',
      '',
      '## Background',
      'The project has two error response formats:',
      '- Format A (correct): writeError(w, r, status, code, msg) producing {"request_id","error_code","message","diagnosis","suggested_action"}',
      '- Format B (wrong): httputil.JSON(w, status, map[string]string{"error": msg}) producing {"error": "msg"}',
      '',
      'Format A is defined in internal/api/handler/error_helper.go via writeError() and writeServiceError().',
      'Error code constants (BAD_REQUEST, NOT_FOUND, INTERNAL_ERROR, etc.) are in internal/api/middleware/error.go.',
      '',
      '## Files to Fix (10 handler files)',
      'All in internal/api/handler/:',
      '- decision.go',
      '- outbox.go',
      '- governance.go',
      '- status.go',
      '- logs.go',
      '- agent_logs.go',
      '- qoder.go',
      '- action.go',
      '- alerts.go',
      '- review.go',
      '',
      '## Replacement Pattern',
      'For each file:',
      '1. Read the file',
      '2. Find all httputil.JSON(w, statusCode, map[string]string{"error": "msg"}) calls',
      '3. Replace with writeError(w, r, statusCode, appropriateErrorCode, "msg")',
      '4. Ensure "baxi/internal/api/middleware" is imported',
      '5. Ensure writeError is accessible (it is in the same package handler)',
      '',
      'Error code mapping:',
      '- StatusBadRequest (400) -> middleware.BAD_REQUEST',
      '- StatusNotFound (404) -> middleware.NOT_FOUND',
      '- StatusInternalServerError (500) -> middleware.INTERNAL_ERROR',
      '- StatusNotImplemented (501) -> middleware.INTERNAL_ERROR',
      '- StatusConflict (409) -> middleware.BAD_REQUEST',
      '',
      'IMPORTANT: Do NOT change httputil.JSON calls that return SUCCESS responses (200, 201, etc.).',
      'Only change ERROR responses (4xx, 5xx) that use map[string]string{"error": ...}.',
      '',
      '## Verification',
      'Run: cd /home/zzz/project/baxi && go build ./...',
      'Run: cd /home/zzz/project/baxi && go test ./internal/api/... -count=1 -v',
      'Run: grep -r "map[string]string{\\"error\\"" internal/api/handler/ to confirm no remaining old format',
    ].join('\n'),
  },
]

const fixResults = await parallel(
  FIX_TASKS.map(t => () =>
    agent(t.prompt, { label: t.label, phase: 'Fix', model: t.model })
  )
)

log('Phase 1 complete: ' + (fixResults?.filter(Boolean).length || 0) + ' agents finished')

// === Phase 2: Verify ===
phase('Verify')

const verifyResults = await parallel([
  () => agent(
    [
      'Run the full Go test suite and build verification for the Baxi project at /home/zzz/project/baxi.',
      '',
      'Execute these commands and report results:',
      '1. cd /home/zzz/project/baxi && go mod tidy 2>&1',
      '2. cd /home/zzz/project/baxi && go build ./... 2>&1',
      '3. cd /home/zzz/project/baxi && go vet ./... 2>&1',
      '4. cd /home/zzz/project/baxi && go test ./... -count=1 -short 2>&1',
      '',
      'If any step fails, report the exact error message and which file/line caused it.',
      '',
      'Report: build_ok (bool), vet_ok (bool), tests_passed (int), tests_failed (int), failures (list of test name + error).',
    ].join('\n'),
    { label: 'Go Verification', phase: 'Verify', model: 'sonnet',
      schema: {
        type: 'object',
        properties: {
          build_ok: { type: 'boolean' },
          vet_ok: { type: 'boolean' },
          tests_passed: { type: 'number' },
          tests_failed: { type: 'number' },
          failures: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                test: { type: 'string' },
                error: { type: 'string' }
              }
            }
          },
          summary: { type: 'string' }
        },
        required: ['build_ok', 'vet_ok', 'tests_passed', 'tests_failed', 'summary']
      }
    }
  ),
  () => agent(
    [
      'Run frontend verification for the Baxi project at /home/zzz/project/baxi/frontend.',
      '',
      'Execute these commands:',
      '1. cd /home/zzz/project/baxi/frontend && npm test -- --run 2>&1',
      '2. cd /home/zzz/project/baxi/frontend && npx tsc --noEmit 2>&1',
      '',
      'Report: tests_passed (int), tests_failed (int), tsc_ok (bool), errors (list).',
    ].join('\n'),
    { label: 'Frontend Verification', phase: 'Verify', model: 'haiku',
      schema: {
        type: 'object',
        properties: {
          tests_passed: { type: 'number' },
          tests_failed: { type: 'number' },
          tsc_ok: { type: 'boolean' },
          errors: { type: 'array', items: { type: 'string' } },
          summary: { type: 'string' }
        },
        required: ['tests_passed', 'tests_failed', 'tsc_ok', 'summary']
      }
    }
  )
])

// === Phase 3: Report ===
phase('Report')

const goV = verifyResults?.[0] || {}
const feV = verifyResults?.[1] || {}

const report = await agent(
  [
    'Generate a concise fix report for the Baxi P1 fixes in Chinese.',
    '',
    '## Fix Summary:',
    '- 5 parallel fix agents executed',
    '- Agent 1 (Opus): GitHub adapter real implementation (CreateIssue, AddLabels, AddComment, Execute)',
    '- Agent 2 (Sonnet): Access control fixes (JSONB conditions, deny-overrides, shouldRedact L-levels, queryLogs error propagation)',
    '- Agent 3 (Sonnet): Infrastructure fixes (pipeline 30min timeout, config sync transaction, MCP pipeline runner)',
    '- Agent 4 (Sonnet): Frontend routes (3 pages) + Handler factory caching (9 methods)',
    '- Agent 5 (Sonnet): Error response format unification (66 call sites across 10 handlers)',
    '',
    '## Verification Results:',
    '- Go: build=' + goV.build_ok + ', vet=' + goV.vet_ok + ', passed=' + goV.tests_passed + ', failed=' + goV.tests_failed,
    '- Frontend: passed=' + feV.tests_passed + ', tsc=' + feV.tsc_ok,
    '',
    'Write a concise report in Chinese covering:',
    '1. Summary of all changes made',
    '2. Test results',
    '3. Any remaining issues or warnings',
    '4. Next steps (P2 items)',
  ].join('\n'),
  { label: 'Fix Report', phase: 'Report', model: 'sonnet' }
)

return {
  fixes: fixResults?.filter(Boolean).length || 0,
  verification: {
    go: verifyResults?.[0],
    frontend: verifyResults?.[1]
  },
  report: report
}
