import json

import config
from adapters.base import ChannelAdapter


class GitHubIssueAdapter(ChannelAdapter):
    """GitHub Issue adapter — formats alert events as GitHub Issues.

    Status: PREVIEW ONLY. Real dispatch is not implemented.
    To enable, set GITHUB_TOKEN env var and implement the GitHub REST API call.
    """

    def __init__(self, dry_run=True):
        self._dry_run = dry_run

    @staticmethod
    def _parse_payload(payload_json):
        try:
            return json.loads(payload_json)
        except (json.JSONDecodeError, TypeError):
            return {}

    def dry_run(self, event: dict) -> dict:
        payload = self._parse_payload(event.get("payload_json"))
        rule_id = payload.get("rule_id", "unknown")
        metric = payload.get("metric_name", "metric")
        current = payload.get("current_value", "N/A")
        baseline = payload.get("baseline_value", "N/A")
        change = payload.get("change_rate", 0)
        severity = payload.get("severity", "medium")
        owner = payload.get("owner_role", "unassigned")

        issue = {
            "title": f"[Alert] {rule_id}: {metric} anomaly detected",
            "body": (
                f"## Alert Details\n\n"
                f"* **Rule**: {rule_id}\n"
                f"* **Metric**: {metric}\n"
                f"* **Current Value**: {current}\n"
                f"* **Baseline**: {baseline}\n"
                f"* **Change**: {change:.1%}\n"
                f"* **Severity**: {severity}\n"
                f"* **Owner**: {owner}\n\n"
                f"---\n"
                f"*Auto-generated by Olist Decision Engine v0.4*"
            ),
            "labels": ["alert", severity, owner],
        }
        return {"status": "preview", "payload": issue, "external_ref": None, "error": None,
                "message": f"[Alert] {rule_id}: {metric}"}

    def dispatch(self, event: dict) -> dict:
        return {"status": "skipped", "external_ref": None,
                "error": "GitHub adapter is dry-run only in v0.4", "message": None}
