// Package outbox provides the repository for ops.outbox_event records.
//
// Outbox events are generated by the pipeline to represent dispatchable actions
// (task assignments, recommendation notifications). The repository handles
// inserting events with idempotent ON CONFLICT semantics — re-running the
// pipeline step does not duplicate events.
package outbox

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
)

// OutboxEvent represents a single row in ops.outbox_event.
type OutboxEvent struct {
	EventID       string
	SourceType    string
	SourceID      string
	EventType     string
	Status        string
	Payload       json.RawMessage
	TargetChannel string
	CreatedAt     time.Time
}

// OutboxRepository handles CRUD operations for ops.outbox_event.
type OutboxRepository struct{}

// NewOutboxRepository creates a new OutboxRepository.
func NewOutboxRepository() *OutboxRepository {
	return &OutboxRepository{}
}

// CreateEvent inserts a single outbox event into ops.outbox_event.
// Returns true if a new row was inserted, false if the event_id already existed
// (ON CONFLICT DO NOTHING).
func (r *OutboxRepository) CreateEvent(ctx context.Context, tx pgx.Tx, event *OutboxEvent) (bool, error) {
	tag, err := tx.Exec(ctx, `
		INSERT INTO ops.outbox_event (
			event_id, event_type, source_type, source_id,
			payload_json, target_channel, status, created_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
		ON CONFLICT (event_id) DO NOTHING
	`,
		event.EventID,
		event.EventType,
		event.SourceType,
		event.SourceID,
		event.Payload,
		event.TargetChannel,
		event.Status,
	)
	if err != nil {
		return false, fmt.Errorf("insert outbox event %s: %w", event.EventID, err)
	}
	return tag.RowsAffected() > 0, nil
}

// CreateEvents inserts multiple outbox events within the same transaction.
// Returns the actual count of newly inserted rows (events that did not already
// exist, determined by ON CONFLICT DO NOTHING).
func (r *OutboxRepository) CreateEvents(ctx context.Context, tx pgx.Tx, events []OutboxEvent) (int64, error) {
	var inserted int64
	for i := range events {
		ok, err := r.CreateEvent(ctx, tx, &events[i])
		if err != nil {
			return inserted, fmt.Errorf("event index %d: %w", i, err)
		}
		if ok {
			inserted++
		}
	}
	return inserted, nil
}
