// Package outbox provides the repository for ops.outbox_event records.
//
// Outbox events are generated by the pipeline to represent dispatchable actions
// (task assignments, recommendation notifications). The repository handles
// inserting events with idempotent ON CONFLICT semantics — re-running the
// pipeline step does not duplicate events.
package outbox

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// OutboxEvent represents a single row in ops.outbox_event.
type OutboxEvent struct {
	EventID          string
	SourceType       string
	SourceID         string
	EventType        string
	Status           string
	Payload          json.RawMessage
	TargetChannel    string
	CreatedAt        time.Time
	DispatchAttempts int64
	NextRetryAt      *time.Time
}

// OutboxRepository handles CRUD operations for ops.outbox_event.
type OutboxRepository struct{}

// NewOutboxRepository creates a new OutboxRepository.
func NewOutboxRepository() *OutboxRepository {
	return &OutboxRepository{}
}

// CreateEvent inserts a single outbox event into ops.outbox_event.
// Returns true if a new row was inserted, false if the event_id already existed
// (ON CONFLICT DO NOTHING).
func (r *OutboxRepository) CreateEvent(ctx context.Context, tx pgx.Tx, event *OutboxEvent) (bool, error) {
	tag, err := tx.Exec(ctx, `
		INSERT INTO ops.outbox_event (
			event_id, event_type, source_type, source_id,
			payload_json, target_channel, status, created_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
		ON CONFLICT (event_id) DO NOTHING
	`,
		event.EventID,
		event.EventType,
		event.SourceType,
		event.SourceID,
		event.Payload,
		event.TargetChannel,
		event.Status,
	)
	if err != nil {
		return false, fmt.Errorf("insert outbox event %s: %w", event.EventID, err)
	}
	return tag.RowsAffected() > 0, nil
}

// CreateEvents inserts multiple outbox events within the same transaction.
// Returns the actual count of newly inserted rows (events that did not already
// exist, determined by ON CONFLICT DO NOTHING).
func (r *OutboxRepository) CreateEvents(ctx context.Context, tx pgx.Tx, events []OutboxEvent) (int64, error) {
	var inserted int64
	for i := range events {
		ok, err := r.CreateEvent(ctx, tx, &events[i])
		if err != nil {
			return inserted, fmt.Errorf("event index %d: %w", i, err)
		}
		if ok {
			inserted++
		}
	}
	return inserted, nil
}

// GetPendingEvents returns pending and failed events available for dispatch,
// using FOR UPDATE SKIP LOCKED for concurrent worker safety.
// Events are ordered by created_at ASC (oldest first) and limited by the
// given limit parameter.
func (r *OutboxRepository) GetPendingEvents(ctx context.Context, pool *pgxpool.Pool, limit int) ([]OutboxEvent, error) {
	rows, err := pool.Query(ctx, `
		SELECT event_id, source_type, source_id, event_type, status,
		       payload_json, target_channel, created_at,
		       dispatch_attempts, next_retry_at
		FROM ops.outbox_event
		WHERE status IN ('pending', 'failed')
		  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
		ORDER BY created_at ASC
		LIMIT $1
		FOR UPDATE SKIP LOCKED
	`, limit)
	if err != nil {
		return nil, fmt.Errorf("query pending outbox events: %w", err)
	}
	defer rows.Close()

	var events []OutboxEvent
	for rows.Next() {
		var e OutboxEvent
		if err := rows.Scan(
			&e.EventID, &e.SourceType, &e.SourceID, &e.EventType,
			&e.Status, &e.Payload, &e.TargetChannel, &e.CreatedAt,
			&e.DispatchAttempts, &e.NextRetryAt,
		); err != nil {
			return nil, fmt.Errorf("scan outbox event: %w", err)
		}
		events = append(events, e)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate outbox event rows: %w", err)
	}
	return events, nil
}

// MarkDispatched updates an outbox event status to 'dispatched', increments
// dispatch_attempts, and records the dispatch time.
func (r *OutboxRepository) MarkDispatched(ctx context.Context, tx pgx.Tx, eventID string) error {
	tag, err := tx.Exec(ctx, `
		UPDATE ops.outbox_event
		SET status = 'dispatched',
		    dispatch_attempts = dispatch_attempts + 1,
		    last_dispatch_at = NOW()
		WHERE event_id = $1
	`, eventID)
	if err != nil {
		return fmt.Errorf("mark outbox event %s as dispatched: %w", eventID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("outbox event %s not found for mark dispatched", eventID)
	}
	return nil
}

// MarkFailed updates an outbox event status to 'failed', increments
// dispatch_attempts, records the dispatch time, and stores the error message.
func (r *OutboxRepository) MarkFailed(ctx context.Context, tx pgx.Tx, eventID string, errMsg string) error {
	tag, err := tx.Exec(ctx, `
		UPDATE ops.outbox_event
		SET status = 'failed',
		    dispatch_attempts = dispatch_attempts + 1,
		    last_dispatch_at = NOW(),
		    error_message = $2
		WHERE event_id = $1
	`, eventID, errMsg)
	if err != nil {
		return fmt.Errorf("mark outbox event %s as failed: %w", eventID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("outbox event %s not found for mark failed", eventID)
	}
	return nil
}

// UpdateMaxAttempts marks an outbox event as permanently failed when the
// worker determines maximum retry attempts have been reached.
func (r *OutboxRepository) UpdateMaxAttempts(ctx context.Context, tx pgx.Tx, eventID string) error {
	tag, err := tx.Exec(ctx, `
		UPDATE ops.outbox_event
		SET status = 'failed',
		    dispatch_attempts = dispatch_attempts + 1,
		    last_dispatch_at = NOW(),
		    error_message = 'max retry attempts reached'
		WHERE event_id = $1
	`, eventID)
	if err != nil {
		return fmt.Errorf("update outbox event %s max attempts: %w", eventID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("outbox event %s not found for max attempts update", eventID)
	}
	return nil
}

// SetNextRetryAt updates the next_retry_at timestamp for an outbox event.
// Used by the dispatch worker to implement exponential backoff after failures.
func (r *OutboxRepository) SetNextRetryAt(ctx context.Context, tx pgx.Tx, eventID string, nextRetryAt time.Time) error {
	tag, err := tx.Exec(ctx, `
		UPDATE ops.outbox_event
		SET next_retry_at = $2
		WHERE event_id = $1
	`, eventID, nextRetryAt)
	if err != nil {
		return fmt.Errorf("set next_retry_at for outbox event %s: %w", eventID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("outbox event %s not found for set next_retry_at", eventID)
	}
	return nil
}

// GetEventByID retrieves a single outbox event by its event_id.
// Returns nil, nil if the event does not exist.
func (r *OutboxRepository) GetEventByID(ctx context.Context, pool *pgxpool.Pool, eventID string) (*OutboxEvent, error) {
	var e OutboxEvent
	err := pool.QueryRow(ctx, `
		SELECT event_id, source_type, source_id, event_type, status,
		       payload_json, target_channel, created_at,
		       dispatch_attempts, next_retry_at
		FROM ops.outbox_event
		WHERE event_id = $1
	`, eventID).Scan(
		&e.EventID, &e.SourceType, &e.SourceID, &e.EventType,
		&e.Status, &e.Payload, &e.TargetChannel, &e.CreatedAt,
		&e.DispatchAttempts, &e.NextRetryAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get outbox event %s: %w", eventID, err)
	}
	return &e, nil
}

// MarkCancelled updates an outbox event status to 'cancelled'.
func (r *OutboxRepository) MarkCancelled(ctx context.Context, tx pgx.Tx, eventID string) error {
	tag, err := tx.Exec(ctx, `
		UPDATE ops.outbox_event
		SET status = 'cancelled'
		WHERE event_id = $1
	`, eventID)
	if err != nil {
		return fmt.Errorf("mark outbox event %s as cancelled: %w", eventID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("outbox event %s not found for mark cancelled", eventID)
	}
	return nil
}
