#!/usr/bin/env python3
"""
db_trigger_simulator.py — Simulate trigger dispatching for v0.2.

Reads event_outbox WHERE status='pending' from SQLite.
By target_channel classifies output:
  - github_issue: generates GitHub Issue payload JSON
  - feishu_cli: generates Feishu CLI command payload
  - local_cli: generates local command suggestion
  - manual: records for human handling

Writes to data/system/trigger_simulation_log.csv
--dry-run: only reads and logs
--apply: also updates event_outbox.status to 'simulated'

Does NOT call GitHub API, Qoder, or send real Feishu messages.
"""

import os
import sys
import csv
import uuid
import json
import datetime
import sqlite3
import argparse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config


DB_PATH = os.path.join(config.PROJECT_ROOT, 'data', 'olist_ops.db')
SYSTEM_DIR = config.SYSTEM_DIR
LOG_FILE = os.path.join(SYSTEM_DIR, 'trigger_simulation_log.csv')


def get_db_connection(db_path=None):
    if db_path is None:
        db_path = DB_PATH
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def generate_github_payload(event):
    """Generate GitHub Issue payload for an alert event."""
    payload = json.loads(event['payload_json'])
    return {
        'channel': 'github_issue',
        'title': f"[Alert] {payload.get('rule_id', 'unknown')}: {payload.get('metric_name', 'metric')} anomaly",
        'body': f"""**Rule**: {payload.get('rule_id')}
**Metric**: {payload.get('metric_name')}
**Current**: {payload.get('current_value')}
**Baseline**: {payload.get('baseline_value')}
**Change**: {payload.get('change_rate', 0):.2%}
**Severity**: {payload.get('severity')}
**Owner**: {payload.get('owner_role')}

*Auto-generated by Olist Decision Engine v0.2*
""",
        'labels': ['alert', payload.get('severity', 'medium'), payload.get('owner_role', 'unassigned')],
    }


def generate_feishu_cli_payload(event):
    """Generate Feishu CLI payload for an alert event."""
    payload = json.loads(event['payload_json'])
    return {
        'channel': 'feishu_cli',
        'command': 'feishu im send',
        'message_type': 'interactive',
        'title': f"[Decision Engine] Alert: {payload.get('rule_id')}",
        'content': f"{payload.get('metric_name')} anomaly detected\n"
                   f"Current: {payload.get('current_value')}\nBaseline: {payload.get('baseline_value')}\n"
                   f"Change: {payload.get('change_rate', 0):.2%}\nOwner: {payload.get('owner_role')}",
        'owner': payload.get('owner_role'),
    }


def generate_local_cli_payload(event):
    """Generate local CLI command suggestion."""
    payload = json.loads(event['payload_json'])
    return {
        'channel': 'local_cli',
        'command': f"python3 scripts/run_alert_detection.py --rule {payload.get('rule_id')} --investigate",
        'description': f"Investigate {payload.get('rule_id')} alert for {payload.get('metric_name')}",
        'owner': payload.get('owner_role'),
    }


def main():
    parser = argparse.ArgumentParser(description='Simulate trigger dispatch for pending outbox events')
    parser.add_argument('--dry-run', action='store_true', help='Only read and log without updating')
    parser.add_argument('--apply', action='store_true', help='Also update outbox status to simulated')
    parser.add_argument('--db', default=DB_PATH, help='Path to SQLite database')
    args = parser.parse_args()

    if args.apply:
        mode = 'apply'
    else:
        mode = 'dry-run'

    print(f"[db_trigger_sim] Mode: {mode}")

    conn = get_db_connection(args.db)
    try:
        # Get pending events
        cur = conn.execute("""
            SELECT outbox_id, event_type, source_type, source_id, payload_json,
                   target_channel, status, created_at
            FROM event_outbox WHERE status = 'pending'
        """)
        pending = cur.fetchall()
        print(f"[db_trigger_sim] Found {len(pending)} pending outbox events")

        if not pending:
            print("[db_trigger_sim] No pending events. Nothing to simulate.")
            return

        # Process each event
        os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
        now = datetime.datetime.now().isoformat()
        log_rows = []

        for event in pending:
            target = event['target_channel']

            if target == 'github_issue':
                gen_payload = generate_github_payload(event)
            elif target == 'feishu_cli':
                gen_payload = generate_feishu_cli_payload(event)
            elif target == 'local_cli':
                gen_payload = generate_local_cli_payload(event)
            else:  # manual or unknown
                gen_payload = {'channel': 'manual', 'description': 'Requires human review',
                              'source_id': event['source_id']}

            log_row = {
                'outbox_id': event['outbox_id'],
                'event_type': event['event_type'],
                'source_id': event['source_id'],
                'target_channel': target,
                'simulated_at': now,
                'mode': mode,
                'generated_payload': json.dumps(gen_payload, ensure_ascii=False),
                'status': 'simulated' if args.apply else 'dry-run',
            }
            log_rows.append(log_row)
            print(f"  [{target}] {event['outbox_id']}: {json.dumps(gen_payload)[:100]}...")

            if args.apply:
                conn.execute("UPDATE event_outbox SET status = 'simulated', processed_at = ? WHERE outbox_id = ?",
                            (now, event['outbox_id']))
                conn.commit()

        # Write simulation log
        with open(LOG_FILE, 'w', newline='', encoding='utf-8') as f:
            if log_rows:
                writer = csv.DictWriter(f, fieldnames=log_rows[0].keys())
                writer.writeheader()
                writer.writerows(log_rows)

        print(f"[db_trigger_sim] Log written to {LOG_FILE} ({len(log_rows)} entries)")
        if args.apply:
            print("[db_trigger_sim] Outbox status updated to 'simulated'")

    except Exception as e:
        conn.rollback()
        print(f"[db_trigger_sim] FAILED: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        conn.close()


if __name__ == '__main__':
    main()
