#!/usr/bin/env python3
"""feishu_cli_probe.py - Feishu CLI capability detection for v0.4."""
import os, sys, subprocess, shutil

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config


def check_credentials():
    app_id = os.environ.get("FEISHU_APP_ID", "")
    app_secret = os.environ.get("FEISHU_APP_SECRET", "")
    chat_id = os.environ.get("FEISHU_CHAT_ID", "")

    if not app_id and os.path.exists(config.FEISHU_APP_CONFIG_FILE):
        import yaml
        with open(config.FEISHU_APP_CONFIG_FILE) as f:
            feishu = yaml.safe_load(f) or {}
        app_id = feishu.get("app_id", "")
        app_secret = feishu.get("app_secret", "")
        chat_id = feishu.get("chat_id", "")

    results = {}
    results["app_id"] = ("PASS" if app_id else "FAIL", app_id[:8] + "..." if app_id else "not set")
    results["app_secret"] = ("PASS" if app_secret else "FAIL", "set" if app_secret else "not set")
    results["chat_id"] = ("PASS" if chat_id else "FAIL", chat_id[:12] + "..." if chat_id else "not set")
    return results


def check_lark_cli():
    path = shutil.which("lark-cli") or shutil.which("lark")
    if not path:
        return ("FAIL", "lark-cli binary not found on PATH")
    try:
        result = subprocess.run([path, "--version"], capture_output=True, text=True, timeout=5)
        version = result.stdout.strip() or result.stderr.strip()
        return ("PASS", f"lark-cli found: {path} (version: {version[:50]})")
    except Exception as e:
        return ("FAIL", f"lark-cli found at {path} but failed: {e}")


def check_lark_oapi():
    try:
        import lark_oapi  # noqa: F401
        version = getattr(lark_oapi, "__version__", "unknown")
        return ("PASS", f"lark-oapi importable (version: {version})")
    except ImportError:
        return ("FAIL", "lark-oapi not installed (pip install lark-oapi)")


def main():
    os.makedirs(config.REPORTS_DIR, exist_ok=True)
    report_path = os.path.join(config.REPORTS_DIR, "feishu_cli_capability_matrix.md")

    results = {
        "Feishu App ID": check_credentials()["app_id"],
        "Feishu App Secret": check_credentials()["app_secret"],
        "Feishu Chat ID": check_credentials()["chat_id"],
        "lark-cli Binary": check_lark_cli(),
        "lark-oapi SDK": check_lark_oapi(),
    }

    print("Feishu CLI Capability Matrix")
    print("=" * 60)
    for name, (status, detail) in results.items():
        print(f"  {name:25s}  {status:6s}  {detail}")
    print("=" * 60)

    lines = [
        "# Feishu CLI Capability Matrix",
        "",
        "| Capability | Status | Detail |",
        "|-----------|--------|--------|",
    ]
    for name, (status, detail) in results.items():
        lines.append(f"| {name} | {status} | {detail} |")
    lines.append("")
    lines.append(f"*Generated by feishu_cli_probe.py*")

    with open(report_path, "w") as f:
        f.write("\n".join(lines))

    print(f"\nReport written to: {report_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
